Repository micaiah-effiong/url-shortener, pull requests merged in 2020-10, with the labels that each got.

#17 Update README.md
  README.md
Labels: documentation

#21 Feat/users
  app.js
  models/users.js
  public/index.html
  public/newfile.html
Labels: enhancement

#25 Login page
  app.js
  public/login.html
  public/stylesheets/style.css
Labels: hacktoberfest-accepted

#26 add readme
  README.md
  package-lock.json
  package.json
Labels: documentation, hacktoberfest-accepted

#29 feat/authentication
  .gitignore
  app.js
  controllers/links.js
  controllers/users.js
  handlers/auth.js
  middlewares/index.js
  middlewares/isAuth.js
  models/links.js
  models/users.js
  package.json
  public/index.html
  public/login.html
  public/scripts/main.js
  public/stylesheets/style.css
  routes/auth.js
  routes/index.js
  routes/links.js
  routes/users.js
Labels: enhancement, hacktoberfest-accepted

#30 feat/user link association
  controllers/auth.js
  controllers/links.js
  controllers/users.js
  models/users.js
  routes/auth.js
  routes/users.js
Labels: enhancement, hacktoberfest-accepted

#33 feat/password reset
  controllers/auth.js
  controllers/links.js
  models/links.js
  models/users.js
  routes/auth.js
Labels: backend, enhancement

#34 create registration page
  public/Registration.html
  public/login.html
Labels: enhancement, frontend

#36 enhance readme
  README.md
Labels: documentation, hacktoberfest-accepted

#35 feat/role access
  controllers/auth.js
  controllers/links.js
  controllers/users.js
  handlers/access-control.js
  handlers/pagination.js
  models/link-matrics.js
  models/links.js
  models/users.js
  package.json
  routes/links.js
Labels: backend, enhancement

#37 feat/link management
  controllers/links.js
  controllers/users.js
  handlers/advanceQuery.js
  handlers/pagination.js
  models/link-matrics.js
  models/links.js
  models/users.js
  public/Registration.html
  public/index.html
  public/login.html
  routes/users.js
Labels: backend, enhancement, hacktoberfest-accepted

#38 feat/link management
  handlers/pagination.js
  package-lock.json
  package.json
  public/.gitignore
  public/README.md
  public/babel.config.js
  public/package-lock.json
  public/package.json
  public/public/favicon.ico
  public/public/index.html
  public/public/old/Registration.html
  public/public/old/build/tailwind.css
  public/public/old/images/Rectangle 4.png
  public/public/old/index.html
  public/public/old/login.html
  public/public/old/scripts/icomoon-free.js
  public/public/old/scripts/iconify.min.js
  public/public/old/scripts/main.js
  public/public/old/scripts/vue.js
  public/public/old/stylesheets/poppins.css
  public/public/old/stylesheets/style.css
  public/public/old/stylesheets/tailwind.css
  public/src/App.vue
  public/src/assets/logo.png
  public/src/components/dashboard.vue
  public/src/components/links-page/links.vue
  public/src/components/manage.vue
  public/src/components/overview.vue
  public/src/components/personal.vue
  public/src/components/side-bar/side-bar.vue
  public/src/main.js
  public/src/router/index.js
Labels: enhancement, frontend

#39 feat/link management
  README.md
  public/package-lock.json
  public/package.json
  public/src/App.vue
  public/src/components/dashboard.vue
  public/src/components/links-page/links.vue
  public/src/components/overview.vue
  public/src/components/statistics-card.vue
Labels: enhancement, frontend
